pipeline {
    agent any

    tools {
        python 'Python310'
    }

    environment {
        IMAGE_NAME = "fraud-detection"
        CONTAINER_NAME = "fraud-api"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/rp7398/real-time-fraud-detection.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'python --version'
                bat 'python -m pip install --upgrade pip'
                bat 'python -m pip install -r requirements.txt'
            }
        }

        stage('Run ETL Pipeline') {
            steps {
                bat 'python src/ingestion/ingest.py'
                bat 'python src/etl/transform.py'
            }
        }

        stage('Train Model') {
            steps {
                bat 'python src/training/train_model.py'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %IMAGE_NAME% -f docker/Dockerfile .'
            }
        }

        stage('Deploy Container') {
            steps {
                bat '''
                docker rm -f %CONTAINER_NAME% || exit 0
                docker run -d -p 5000:5000 --name %CONTAINER_NAME% %IMAGE_NAME%
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
