pipeline {
    agent any

    environment {
        PYTHON_EXE = 'C:\\Users\\Rajat Pathak\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'
        IMAGE_NAME = 'fraud-detection'
        CONTAINER_NAME = 'fraud-api'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/rp7398/real-time-fraud-detection.git'
            }
        }

        stage('Verify Python') {
            steps {
                bat '"%PYTHON_EXE%" --version'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '"%PYTHON_EXE%" -m pip install --upgrade pip'
                bat '"%PYTHON_EXE%" -m pip install -r requirements.txt'
            }
        }

        stage('Run ETL Pipeline') {
            steps {
                bat '"%PYTHON_EXE%" src/ingestion/ingest.py'
                bat '"%PYTHON_EXE%" src/etl/transform.py'
            }
        }

        stage('Train Model') {
            steps {
                bat '"%PYTHON_EXE%" src/training/train_model.py'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %IMAGE_NAME% -f docker/Dockerfile .'
            }
        }

        stage('Deploy Container') {
            steps {
                bat '''
                docker rm -f %CONTAINER_NAME% || exit 0
                docker run -d -p 5000:5000 --name %CONTAINER_NAME% %IMAGE_NAME%
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
