pipeline {
    agent any

    environment {
        IMAGE_NAME = "fraud-detection"
        CONTAINER_NAME = "fraud-api"
    }

    stage('Checkout Code') {
    steps {
        git branch: 'main',
            url: 'https://github.com/rp7398/real-time-fraud-detection.git',
            credentialsId: 'github-token'
    }
}

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Data Pipeline') {
            steps {
                sh 'python src/ingestion/ingest.py'
                sh 'python src/etl/transform.py'
            }
        }

        stage('Train Model') {
            steps {
                sh 'python src/training/train_model.py'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME -f docker/Dockerfile .'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f $CONTAINER_NAME || true
                docker run -d -p 5000:5000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo "Fraud Detection API deployed successfully"
        }
        failure {
            echo "Pipeline failed"
        }
    }
}
